n = input('Digite uma frase:')
print('O tipo primitivo desse valor é {}'.format(type(n)))
print('É numérico? {}'.format(n.isnumeric()))
print('É alfabético? {}'.format(n.isalpha()))
print('É alfanumérico? {}'.format(n.isalnum()))
print('Esta escrito somente em minúsculas? {}'.format(n.islower()))
print('Esta escrito somente em maiúsculas? {}'.format(n.isupper()))
print('É capitalizado? {}'.format(n.istitle()))
print('É composto somente de espaços? {}'.format(n.isspace()))
